name: workmetric
description: A Flutter app with GetX + Firebase demonstrating Manager & Worker roles (detailed skeleton).
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  geolocator: ^13.0.1
  geocoding: ^2.0.5
  intl: ^0.18.0
  permission_handler: ^11.3.0
  flutter_launcher_icons: ^0.10.0
  slide_to_act: ^2.0.2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
